language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn verify deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: j4wCbNIj62CKJ39mMJumbPz9NFF8HMQKLVehO9Naq4HtX9IbR0XEv2nYa2ldaIM5Gi3Ki2ikHHZRx+OOnapWjthRWhW0dzNzqdGfAi1heOHB9xLT1xYjS1PiscI88+ip1s8Hc4b0A8v0FSQRa+QtzIoX9srpQiUHwEzXGsunz+E=
  # SONATYPE_PASSWORD
  - secure: SeLijG5ju4hzdoz96irT4LvfRLpQk/4B25NMKME9tRgo9Oz61WgrFmm08iuft1NeLT36jDeHl1uEhYx3VJlHfFSueFw1emX2HLTazyAOfl7Ip/5g0DW04AmSYAJnA8RyoP24fE3qib8Uby8YoddUdJot5gMV1aqh0KuV9jBV+Ho=
  # GPG_PASSPHRASE
  - secure: FC1sR0dbWExJZERAAk6+4I028JRpW29tY8ngq7fWNPDW67gfvxXHAPV6SpJP6awMu0CRdKg8ANTinM+3AMxXEuKXeJTScVKdzwdoQzLru1toKypor4NrjnBck+i8gHP36BgvJo7YEfspaTRTILyYYTITmYTMK8xic7LIKrSu2GI=
  # GPG_KEYID
  - secure: HnMRlqVdjEspQ1oE7wfqhzo95PhFcx5sJhJul7J+P/jXIarwqtmIaQVCjk1C2jMhGrMtslpak1Y/pob8dqrGGtuleoGIQnxddYSFyoCDkPwkZaupeoY6oiQEAOCXpDOLLxjxjSYMQFB9DXRdQzsnn8sz8iwRBvZn9LHdbSxJS28=
  # GPG_KEY
  - secure: ls2sWTc2D6m4rqzu+aIqk2KscWsm2FRbEowez0kRuosW5An/BrjjCFGYVNzovgMMCfnwdNrVlDEgN9jyUUSfZS+zpZmvqi5+OwGnFOi5BhdAq/DvNOi8+2x95dJ7EWHNiowfR8b3PsA4AWvfZfthyDE4B7YZ2UQxbDlht5vujh8=
